#!/usr/bin/env python

# strip module
x = " Hello, World! "
print(x.strip())

# lower module
x = "hello world!"
print(x.lower())

# upper module
x = "hello world"
print(x.upper())

# replace modeule
x = "Hello world!"
print(x.replace("H","J"))

# split module
x = "Hello, world!"
print(x.split(","))

# check string
txt = "the rain in spain stays mainly in the plain"
x = "ain" in txt
print(x)

# concat module
a = "hello"
b = "world"
c = a + b
print(c)
